created filereader.cpp and filereader.h / Parser
Vasqq/Air_Traffic_Control_System pull request #19
Opened 2023-03-18 17:10 UTC by fahimbhuiyan

class that reads an input file containing data about scheduled airplane flights, and extracts the relevant information into an internal schedule vector of aircraft objects.

2023-03-18 17:11 UTC, fahimbhuiyan commented
issue #2

2023-03-19 14:42 UTC, Vasqq requested changes
Please see comments and delete all the .dstore files along with the .json file and re commit so we don't merge them to main.

2023-03-19 14:42 UTC, Vasqq commented on .DS_Store
Don't need to commit this.

2023-03-19 14:42 UTC, Vasqq commented on .vscode/c_cpp_properties.json
Don't need to commit this.

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/.DS_Store
Don't need to commit this.

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/src/.DS_Store
Don't need to commit this.

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/src/FileReader.cpp
> +	//LOG_DEBUG("Planes in cycle %d: %d\n",timeVal, ret.size());
Remove dead code.

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/src/FileReader.h
> +#endif /* SRC_FILEREADER_H_ */
here

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/src/FileReader.h
> +#define SRC_FILEREADER_H_
here

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/src/FileReader.h
> +#ifndef SRC_FILEREADER_H_
here

2023-03-19 14:42 UTC, Vasqq commented on Air_Traffic_Control_System/src/FileReader.h
Change name to Parser.h
** DON'T FORGET TO CHANGE THE #ifndef AND #define AS WELL!

ex// SRC_FILEREADER_H_ becomes SRC_PARSER_H_

2023-03-19 14:42 UTC, Vasqq commented on Documentation/.DS_Store
Don't need to comit this.

2023-03-21 21:35 UTC, fahimbhuiyan commented on Air_Traffic_Control_System/src/FileReader.cpp
> +	//LOG_DEBUG("Planes in cycle %d: %d\n",timeVal, ret.size());
done

2023-03-21 21:36 UTC, fahimbhuiyan commented on Air_Traffic_Control_System/src/FileReader.h
> +#ifndef SRC_FILEREADER_H_
done

2023-03-21 21:36 UTC, fahimbhuiyan commented on Air_Traffic_Control_System/src/FileReader.h
> +#define SRC_FILEREADER_H_
done

2023-04-11 02:53 UTC, closed without merging